### ISSUE TITLE
Suggestion responds with empty move list

### ISSUE THREAD

**Issue by daymxn** [MinusKelvin/cold-clear-2#3]
I'm not super familiar with rust, so my ability to debug the issue is fairly limited. I tried reading through the source, and it does seem like the deserialization present in CC2 is different than the current tbp-spec. Specifically, with how the `start` message is represented. Although, tbf, the documentation for the tbp-spec could just be leaving out some information that CC2 accounts for. Anyhow, on to the issue.

I've tried various forms of the `start` message, followed by a `suggest` message, all of which end in CC2 sending this suggestion:
```json
{
  "type": "suggestion",
  "moves": [],
  "move_info": {
    "nodes": 0,
    "nps": 0.0,
    "extra": "0.0% of selections expanded, overall speed: 0.0 Mnps"
  }
}
```

As you can see, the `moves` list is empty, and the `move_info` represents that as well.

This could all be just me misinterpreting how `start` message is supposed to look as well, so if you could offer an example for me to test- that'd be greatly appreciated as well :')

**Comment by MinusKelvin** [comment]
I can't help much if you don't provide any way to reproduce the issue, but an example of a start message is
```json
{
   "back_to_back" : false,
   "board" : ...,
   "combo" : 0,
   "hold" : null,
   "queue" : [
      "S",
      "Z"
   ],
   "type" : "start"
}
```
I've omitted the board attribute for brevity.

**Comment by daymxn** [comment]
I appreciate the response! I've actually narrowed down the issue. When the queue only contains a single item- the moves list is empty. Is this a bug or is it intentional?

```json
{
  "type": "start",
  "hold": null,
  "queue": [ "S" ],
  "combo": 0,
  "back_to_back": false,
  "board": ...
}
```

```json
{
  "type": "suggestion",
  "moves": [],
  "move_info": {
    "nodes": 0,
    "nps": 0,
    "extra": "0.0% of selections expanded, overall speed: 0.0 Mnps"
  }
}
```

**Comment by MinusKelvin** [comment]
This is an intentional omission. In most games, the queue is several pieces long, and even when restricted to a single-piece queue, the 7-bag randomizer is being used, which CC2 understands and will return a move list including a placement for each possible remaining piece. This approach is not generally applicable when the 7-bag randomizer is not being used, although I suppose it would be preferable to still return a placement in this case.
